#!/usr/bin/env python3

from tkinter import *
import math
# ---------------------------- CONSTANTS ------------------------------- #
PINK = "#e2979c"
RED = "#e7305b"
GREEN = "#9bdeac"
YELLOW = "#f7f5dd"
FONT_NAME = "Courier"
WORK_MIN = 25*60
SHORT_BREAK_MIN = 5*60
LONG_BREAK_MIN = 30*60
reps = 0
timer = None

# ---------------------------- TIMER RESET ------------------------------- # 
def reset():
    global reps
    window.after_cancel(timer)
    label.config(text="Timer")
    canvas.itemconfig(timer_text, text="00:00")
    check_mark.config(text="")
    reps = 0
# ---------------------------- TIMER MECHANISM ------------------------------- # 
def start_timer():
    global reps
    if reps <= 8:
        reps += 1
    else:
        reps = 0
    if reps % 8 == 0:
        count_down(LONG_BREAK_MIN)
        label.config(text="BREAK", font=(FONT_NAME, 36), bg=YELLOW, fg=RED)
    elif reps % 2 == 0:
        count_down(SHORT_BREAK_MIN)
        label.config(text="BREAK", font=(FONT_NAME, 36), bg=YELLOW, fg=PINK)
    else:
        count_down(WORK_MIN)
        label.config(text="WORK", font=(FONT_NAME, 36), bg=YELLOW, fg=GREEN)


# ---------------------------- COUNTDOWN MECHANISM ------------------------------- # 
def count_down(count):
        global timer
        count_min = math.floor(count/60)
        count_sec = count%60
        if count_min < 10:
            count_min = f"0{count_min}"
        if count_sec < 10:
            count_sec = f"0{count_sec}"
        canvas.itemconfig(timer_text, text=f"{count_min}:{count_sec}")
        if count > 0:
            timer = window.after(1000, count_down, count - 1)
        else:
            start_timer()
            if reps % 2 == 0:
                ticks = "✓" * int(reps/2)
                check_mark.config(text=ticks)


# ---------------------------- UI SETUP ------------------------------- #
window = Tk()
window.title("Pomodoro Timer")
window.config(padx=100, pady=50, bg=YELLOW)

canvas = Canvas(width=200, height=224, bg=YELLOW, highlightthickness=0)
tomato_img = PhotoImage(file="tomato.png")
canvas.create_image(100, 112, image=tomato_img)
timer_text = canvas.create_text(100, 130, text="00:00", fill='white', font=(FONT_NAME, 35, 'bold'))
canvas.grid(row=2, column=2)

label = Label(text="Timer", font=(FONT_NAME, 36), bg=YELLOW, fg=GREEN)
label.grid(row=1, column=2)


button_start = Button(width=2, text="Start", command=start_timer, highlightthickness=0)
button_start.grid(row=3, column=0)
button_stop = Button(width=2, text="Reset", command=reset, highlightthickness=0)
button_stop.grid(row=3, column=3)

check_mark = Label(text="", bg=YELLOW, fg=RED)
check_mark.grid(row=4, column=2)

# checkbutton.config(pady=50)

window.mainloop()